### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by d0peCode** [kasvith/express-mongo-jwt-boilerplate#13]
We have two deprecation warnings:

- DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.

- DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.

I created PR with fix #14.

<hr>

**Edit**

I also updated dependencies.

**Comment by kasvith** [comment]
Closed by #14
